config/routes.rb
Rails.application.routes.draw do

    get 'userDashboard' => 'home#user_dashboard' , as: :user_dashboard

    get 'Availability' => 'home#seat_availability', as: :seat_availability
    get 'BookRooms' => 'home#book_rooms', as: :book_rooms
    get 'available-rooms' => 'home#search_available_rooms', as: :search_available_rooms
    post 'book-room' => 'home#booked_room', as: :booked_room

  root 'home#index'

  Rails.application.routes.draw do
    devise_for :users, controllers: {
        confirmations: 'users/confirmations',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        sessions: 'users/sessions'
    }
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :member
      # can :create, :MODEL
      # can :update, :all
      # can :read, :all
      can :read, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/booking_status.rb
class BookingStatus < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :room_category
  has_many :booking_statuses
end

app/models/room_category.rb
class RoomCategory < ActiveRecord::Base
  has_many :rooms
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_filter :set_cache_buster

 # Set the after sign in path for user
  def after_sign_in_path_for(resource)
   user_dashboard_path
  end

  protected
  # Added the method so that user can not redirect to back to his dashboard if he logs out.
    def set_cache_buster
      response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
      response.headers["Pragma"] = "no-cache"
      response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [ :user_dashboard ]
  include HomeHelper

# Index action to shoe home page for non logged in user
  def index

  end
# Method for user dashboard and show user booking statuses.
  def user_dashboard
    @room_id = BookingStatus.where(user_id:current_user).pluck(:room_id).uniq

  end

# Method to search available rooms
  def search_available_rooms
    room_type = params[:room_type].to_i
    start_date = params[:start_date]
    end_date = params[:end_date]
    booked_rooms = find_available_rooms(room_type, start_date, end_date)
    booked_rooms_id = []
    booked_rooms.each do |room|
      booked_rooms_id.push(room.room_id)
    end
    filtered_rooms_on_room_type = RoomCategory.find(room_type).rooms.pluck(:id)
    @available_rooms = filtered_rooms_on_room_type - booked_rooms_id
    respond_to do |format|
      format.html
      format.js
    end
  end

# Method for booking the rooms
  def booked_room
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    (start_date..end_date).each do |date|
      booked_room = BookingStatus.new(
          start_date: date,
          user_id: current_user.id,
          room_id: params[:room_id]
      )

      booked_room.save
    end
  end

# Method for showing the room categories
  def book_rooms
    @room_category= RoomCategory.all
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]


  protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit( :email, :password,
                      :first_name, :last_name, :company_name, roles: [])}
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit( :email, :password,
                      :first_name, :last_name, :company_name, roles: [])}
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

# Query to retreive categories wise booked rooms
  def find_available_rooms(room_type, start_date, end_date)

    query = "SELECT result.*, booking_statuses.* FROM
                (SELECT rooms.id, rooms.number, rooms.room_category_id from rooms
                  INNER JOIN room_categories
                  ON room_categories.id = rooms.room_category_id AND room_categories.id = #{room_type}
                )
                AS result
                  INNER JOIN booking_statuses
                  ON booking_statuses.room_id = result.id AND booking_statuses.start_date BETWEEN '"+ start_date + "' AND '" +
                  end_date + "'"
    result = BookingStatus.find_by_sql(query)
  end
end

app/views/home/_search_available_rooms.html.haml
%h1 Available Rooms from  #{params[:start_date].to_time.strftime("%m/%d/%y")} to #{params[:end_date].to_time.strftime('%m/%d/%y')}
.panel
  .table-responsive
    %table.table{:style => "margin-bottom: 0px;"}
      %thead
        %tr
          %th Room Number
          %th Room Type
          %th Price
          %th
      %tbody
        - @available_rooms.each do |room_id|
          - room = Room.find_by_id(room_id)
          %tr
            %td
              = room.number
            %td
              = room.room_category.category
            %td
              = room.room_category.price
            %td
              = button_to "Book", booked_room_path(room_id: room, start_date: params[:start_date],end_date: params[:end_date]),class:'book-button'

app/views/home/book_rooms.html.haml
%head
= render 'layouts/dashboard_header'
%br
%br
%h3.align-heading
  Book your Room
.container.form-label
  .form-control-static
    = form_tag search_available_rooms_path, method: 'get', remote: true do
      .col-md-12.col-lg-12
        .col-md-3.col-lg-3
          %label Start Date
        .col-md-3.col-lg-3
          %label End Date
        .col-md-6.col-lg-6
          %label Room Type
      = date_field_tag(:start_date, Date.today, class: 'datepicker')
      = date_field_tag(:end_date, Date.today, class: 'datepicker')
      = select_tag(:room_type, options_for_select(@room_category.map{ |c| [c.category + '(' + c.price.to_s + ' RS' + ')', c.id ]}))
      = submit_tag('Search Rooms',class:'search-button')
    #booking-page

app/views/home/booked_room.html.haml
= render 'layouts/dashboard_header'
.room-status
  %h1 Your room is booked

app/views/home/index.html.haml
#home
  .overlay
    / overylay class usage
    .container
      .col-md-8.col-md-offset-2.text-center
        %h1 HOTEL MANAGEMENT SYSTEM
  = render 'layouts/footer'

app/views/home/search_available_rooms.js.erb
$('#booking-page').html("<%= escape_javascript(render partial: 'search_available_rooms') %>")

app/views/home/user_dashboard.html.haml
%head
= render 'layouts/dashboard_header'
%br
%br
%h1
  WELCOME #{current_user.first_name.capitalize}  #{current_user.last_name.capitalize}
.book-room-link
  = link_to 'Book Room',book_rooms_path
.panel.col-md-6.col-lg-6
  %h3.text-center  Booking Statuses
  .user-booked-rooms-status
    .table-responsive
      %table.table{:style => "margin-bottom: 0px;"}
        %thead
          %tr
            %th Room Number
            %th Room Type
        %tbody
          - @room_id.each do |room_id|
            - room = Room.find_by_id(room_id)
            %tr
              %td
                = room.number
              %td
                = room.room_category.category

app/views/layouts/_dashboard_header.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => '.navbar-collapse', "data-toggle" => 'collapse', :type => 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse.navbar-right.scroll-me
      %ul.nav.navbar-nav
        %li.username
          %a{:href => "#"}
            .pull-left
            .pull-right
              %span
                =  "#{current_user.first_name}".capitalize + " "+"#{current_user.last_name}".capitalize
        %li
          - if user_signed_in?
            = link_to "Logout", destroy_user_session_path, method: :delete

app/views/layouts/_flash_message.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    = value

app/views/layouts/_footer.html.haml
%footer
  .container
    .col-md-12
      %ul.list-inline.quicklinks
        %li
          %h3 All Rights Reserved @2016

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => '.navbar-collapse', "data-toggle" => 'collapse', :type => 'button'}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .navbar-collapse.collapse.navbar-right.scroll-me
      %ul.nav.navbar-nav
        %li
          = link_to "Sign Up", new_user_registration_path
        %li
          - if user_signed_in?
            = link_to "Logout", destroy_user_session_path, method: :delete
          - else
            = link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %meta{:charset => 'utf-8'}
    %meta{:content => 'width=device-width, initial-scale=1, maximum-scale=1', :name => 'viewport'}
    %title Hotel Management
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/